#!/bin/bash
path=$1
if [ $(uname) = 'Darwin' ] ; then
  targetPath=$(greadlink -f $path)
else
  targetPath=$(readlink -f $path)
fi
#echo $targetPath

for i in $(find $targetPath -type d -maxdepth 1  -not -name ".*"); do

    if [[ ! $i = $targetPath ]] && [[ ! ${i##*/} = zManager ]]&& [[ ! ${i##*/} = .git ]]; then
      echo --- $i ------------------
      for j in $(find $i -name '*.ipynb'); do
        if [ `expr "$j" : '.*\/\.'` -eq 0 ]; then #Path에 숨김파일 없으면
          echo ' ' $j
          j2m $j
        fi
      done

    fi
done
