#!/usr/local/opt/python@3.9/bin/python3.9
# -*- coding: utf-8 -*-

# Source : https://github.com/Finfra/Converter_py-ipynb-md.git

import re
import sys
from p2j.p2j import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
